model:
    name: two_view_pipeline
    extractor:
      name: extractors.aliked
      max_num_keypoints: 2048
      detection_threshold: 0.0
    segment:
      name: segments.segment
      num_classes: 150 #lightglue配置中有个default_conf segementi_dim需要设置
      #stochastic_drop_path: 2e-1
      #backbone 
      embed_dims: [32,64,160,256]
      norm_typ: 'SyncBN' # norm_cfg = dict(type='SyncBN', requires_grad=True)
      
      #Hamburger Parameters
      ham_channels: 256 #ham_channels输入hamburger的通道
      put_cheese: True

      DUAL: False
      SPATIAL: True
      RAND_INIT: True

      MD_S: 1
      MD_D: 512
      MD_R: 64

      TRAIN_STEPS: 6
      EVAL_STEPS: 6

      INV_T: 1
      BETA: 0.1
      Eta: 0.9
    matcher:
      name: matchers.lightglue
      features: aliked
      depth_confidence: -1
      width_confidence: -1
      filter_threshold: 0.1
      segment_dim: 480 #segment维度
benchmarks:
    megadepth1500:
      data:
        preprocessing:
          side: long
          resize: 1600
      eval:
        estimator: opencv
        ransac_th: 0.5
    hpatches:
      eval:
        estimator: opencv
        ransac_th: 0.5
      model:
        extractor:
          max_num_keypoints: 1024  # overwrite config above
