model:
    name: two_view_pipeline
    extractor:
      name: gluefactory_nonfree.superpoint
      max_num_keypoints: 2048
      detection_threshold: 0.0
      nms_radius: 3
    extractor_dino:
      name: backbones.dinov2_pipeline
      allow_resize: True
    matcher:
      name: matchers.lightglue
      features: superpoint
      depth_confidence: -1
      width_confidence: -1
      filter_threshold: 0.1
      n_layers: 9
      segment_dim: 768 
benchmarks:
    megadepth1500:
      data:
        preprocessing:
          side: long
          resize: 1600 #1024
      eval:
        estimator: opencv
        ransac_th: 0.5
    hpatches:
      eval:
        estimator: opencv
        ransac_th: 0.5
      model:
        extractor:
          max_num_keypoints: 1024 #1024  # overwrite config above
